- name: Check if kubectl is available
  command: kubectl version --client=true --short
  register: kubectl_version
  changed_when: false

- name: Display kubectl Version
  debug:
    var: kubectl_version.stdout

- name: Get Kubernetes Nodes
  command: kubectl get nodes
  register: nodes
  changed_when: false

- name: Show Nodes
  debug:
    var: nodes.stdout_lines

- name: Get Kubernetes Pods
  command: kubectl get pods -A
  register: pods
  changed_when: false

- name: Show Pods
  debug:
    var: pods.stdout_lines
