- name: Apply Kubernetes deployment
  shell: kubectl apply -f ../k8s/deployment.yaml
  args:
    chdir: "{{ playbook_dir }}"

- name: Apply Kubernetes service
  shell: kubectl apply -f ../k8s/service.yaml
  args:
    chdir: "{{ playbook_dir }}"
