apiVersion: v1
kind: Service
metadata:
  name: coco-frontend-service
spec:
  type: NodePort
  selector:
    app: coco
  ports:
    - port: 4173
      targetPort: 4173
      nodePort: 30173  # Minikube will expose this
